search_keywords:
  - GTX 1660
  - GTX 1660 Ti
  - GTX 1070
  - GTX 1080 Ti
  - RTX 2060 Super
  - RTX 2070
  - RTX 2070 Super
  - RTX 2080 Super
  - RTX 2080 Ti

  - RTX 3060 LHR
  - RTX 3060 Ti LHR
  - RTX 3060 Ti
  - RTX 3070 LHR
  - RTX 3070
  - RTX 3070 Ti
  - RTX 3080 LHR
  - RTX 3080
  - RTX 3080 Ti
  - RTX 3090
  - RTX A2000 6Gb
 
  - RX 470
  - RX 570
  - RX 580
  - RX 5500 XT
  - RX 5600 XT
  - RX 5700
  - RX 5700 XT
  - RX 6500
  - RX 6600
  - RX 6600 XT
  - RX 6700
  - RX 6700 XT
  - RX 6800
  - RX 6800 XT
  - RX 6900 XT
  - VEGA 56
  - VEGA 64
  - BC-160
  - Radeon VII


# log_level: DEBUG